### ISSUE TITLE
Mono 4.3.x / 4.4 (upcoming)

### ISSUE THREAD

**Issue by rapgro** [restsharp/RestSharp#823]
$ xbuild RestSharp.Net45.Signed.csproj
…
CSC:  warning CS2029: Invalid conditional define symbol `'
CSC:  warning CS2029: Invalid conditional define symbol`'
CSC:  warning CS1691: `1658' is not a valid warning number
CSC: error CS1904:`1658' is not a valid warning number
    Task "Csc" execution -- FAILED
    Done building target "CoreCompile" in project "/builddir/build/BUILD/RestSharp-105.2.3/RestSharp.Net45/RestSharp.Net45.Signed.csproj".-- FAILED
Done building project "/builddir/build/BUILD/RestSharp-105.2.3/RestSharp.Net45/RestSharp.Net45.Signed.csproj".-- FAILED
Build FAILED.
Warnings:
/builddir/build/BUILD/RestSharp-105.2.3/RestSharp.Net45/RestSharp.Net45.Signed.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->
    CSC:  warning CS2029: Invalid conditional define symbol `'
    CSC:  warning CS2029: Invalid conditional define symbol`'
    CSC:  warning CS1691: `1658' is not a valid warning number
Errors:
/builddir/build/BUILD/RestSharp-105.2.3/RestSharp.Net45/RestSharp.Net45.Signed.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->
    CSC: error CS1904:`1658' is not a valid warning number
     3 Warning(s)
     1 Error(s)

**Comment by rapgro** [comment]
Timotheus Pokorra 2016-03-07 09:01:36 CET

Comparing with previous builds of RestSharp, this error used to be a warning:

CSC:  warning CS2029: Invalid conditional define symbol `'
CSC:  warning CS2029: Invalid conditional define symbol `'
CSC:  warning CS1691: `1658' is not a valid warning number

So I guess, with Mono 4.3.2 this has now become an error.

I find/grepped for 1658, and found it was in some csproj files in a NoWarn tag.
So that invalid warning number can be removed there.

This works for me locally, when I add these lines to the %prep section in restsharp.spec:

sed -i 's#,1658</NoWarn>#</NoWarn>#g' RestSharp.Net45/RestSharp.Net45.Signed.csproj
sed -i 's#,1658</NoWarn>#</NoWarn>#g' RestSharp.Net45/RestSharp.Net45.Signed.csproj
sed -i 's#,1658</NoWarn>#</NoWarn>#g' RestSharp/RestSharp.Net35.csproj

Downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1315057

**Comment by alexeyzimarev** [comment]
RestSharp will not be building on Mono since it is moved to the VS 2017 csproj file format. You can use .NET Standard library and it should work with Mono 5.4
